# Generated by Django 4.1.1 on 2022-10-05 23:00

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models
import django.utils.timezone
import django_countries.fields
import model_utils.fields
import mysite.core.validators
import phonenumber_field.modelfields
import recurrence.fields
import upload_validator


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutPage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
                ("introduction", ckeditor.fields.RichTextField(blank=True)),
                ("introduction_image", models.ImageField(blank=True, upload_to="images/")),
                ("history", ckeditor.fields.RichTextField(blank=True)),
                ("history_image", models.ImageField(blank=True, upload_to="images/")),
                (
                    "doctrine",
                    ckeditor.fields.RichTextField(blank=True, help_text="A brief statement sumarizing our beliefs"),
                ),
                ("doctrine_image", models.ImageField(blank=True, upload_to="images/")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Belief",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
                (
                    "icon",
                    models.FileField(
                        blank=True,
                        help_text="Only SVG, JPEG and PNG Image files accepted",
                        upload_to="images/icons/",
                        validators=[
                            upload_validator.FileTypeValidator(
                                allowed_extensions=[".svg", ".png", ".jpg", ".jpeg"],
                                allowed_types=["image/svg+xml", "image/png", "image/jpeg"],
                            ),
                            mysite.core.validators.validate_icon_size,
                        ],
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HomePage",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
                ("welcome_message", ckeditor.fields.RichTextField()),
                ("welcome_image", models.ImageField(blank=True, upload_to="images/")),
                ("beliefs_heading", models.CharField(default="Our Beliefs", max_length=255)),
                ("beliefs_subheading", ckeditor.fields.RichTextField(blank=True)),
                ("weekly_activities_heading", models.CharField(default="Weekly Activities", max_length=255)),
                ("weekly_activities_subheading", ckeditor.fields.RichTextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
                ("street_address", models.CharField(max_length=255)),
                ("postal_address", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ("email", models.EmailField(blank=True, max_length=254)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Mission",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="OnlinePlatforms",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("facebook", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("sermon_audio", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("facebook_livestream", models.BooleanField(default=False, help_text="Do you stream to Facebook?")),
                ("youtube_livestream", models.BooleanField(default=False, help_text="Do you stream to YouTube?")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Vision",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="WeeklyActivity",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="created"
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now, editable=False, verbose_name="modified"
                    ),
                ),
                (
                    "status",
                    model_utils.fields.StatusField(
                        choices=[("published", "published"), ("draft", "draft")],
                        default="published",
                        max_length=100,
                        no_check_for_status=True,
                        verbose_name="status",
                    ),
                ),
                (
                    "status_changed",
                    model_utils.fields.MonitorField(
                        default=django.utils.timezone.now, monitor="status", verbose_name="status changed"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", autoslug.fields.AutoSlugField(editable=False, populate_from="title", unique=True)),
                ("description", models.TextField()),
                ("start", models.TimeField()),
                ("end", models.TimeField()),
                ("recurrences", recurrence.fields.RecurrenceField()),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
